INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, LOGIN, EMAIL) VALUES (100, '1', '1', '1', '1');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, LOGIN, EMAIL) VALUES (200, '2', '2', '2', '2');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, LOGIN, EMAIL) VALUES (300, '3', '3', '3', '3');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, LOGIN, EMAIL) VALUES (400, '4', '4', '4', '4');
