CREATE TABLE "USER" (
    "ID" int(11) NOT NULL AUTO_INCREMENT,
    "FIRST_NAME" VARCHAR(60) NOT NULL,
    "LAST_NAME" VARCHAR(60) NOT NULL,
    "LOGIN" VARCHAR(60) NOT NULL,
    "EMAIL" VARCHAR(60) NOT NULL,
    PRIMARY KEY ("ID")
);